//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ConsoleApplication1.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ImportDataServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Result))]
    public partial class ImportDataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAttachmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback NoReceiveDatasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveDatasOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveHLFJListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveHLFJOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveLxjzDatasOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpLoadFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteTaskDbOperationCompleted;
        
        private System.Threading.SendOrPostCallback BackDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback OSSShptodbOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLayerStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryLayerOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadattachmsgOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ImportDataService() {
            this.Url = global::ConsoleApplication1.Properties.Settings.Default.ConsoleApplication1_WebReference_ImportDataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAttachmentCompletedEventHandler GetAttachmentCompleted;
        
        /// <remarks/>
        public event NoReceiveDatasCompletedEventHandler NoReceiveDatasCompleted;
        
        /// <remarks/>
        public event ReceiveDatasCompletedEventHandler ReceiveDatasCompleted;
        
        /// <remarks/>
        public event SaveHLFJListCompletedEventHandler SaveHLFJListCompleted;
        
        /// <remarks/>
        public event SaveHLFJCompletedEventHandler SaveHLFJCompleted;
        
        /// <remarks/>
        public event ReceiveLxjzDatasCompletedEventHandler ReceiveLxjzDatasCompleted;
        
        /// <remarks/>
        public event UpLoadFileCompletedEventHandler UpLoadFileCompleted;
        
        /// <remarks/>
        public event ImportDataCompletedEventHandler ImportDataCompleted;
        
        /// <remarks/>
        public event DeleteTaskDbCompletedEventHandler DeleteTaskDbCompleted;
        
        /// <remarks/>
        public event BackDataCompletedEventHandler BackDataCompleted;
        
        /// <remarks/>
        public event OSSShptodbCompletedEventHandler OSSShptodbCompleted;
        
        /// <remarks/>
        public event UpdateLayerStateCompletedEventHandler UpdateLayerStateCompleted;
        
        /// <remarks/>
        public event QueryLayerCompletedEventHandler QueryLayerCompleted;
        
        /// <remarks/>
        public event UploadattachmsgCompletedEventHandler UploadattachmsgCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAttachment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SingleResultOfArrayOfByte GetAttachment(string xzqdm, string tblx, string tbbh, string attachmentName) {
            object[] results = this.Invoke("GetAttachment", new object[] {
                        xzqdm,
                        tblx,
                        tbbh,
                        attachmentName});
            return ((SingleResultOfArrayOfByte)(results[0]));
        }
        
        /// <remarks/>
        public void GetAttachmentAsync(string xzqdm, string tblx, string tbbh, string attachmentName) {
            this.GetAttachmentAsync(xzqdm, tblx, tbbh, attachmentName, null);
        }
        
        /// <remarks/>
        public void GetAttachmentAsync(string xzqdm, string tblx, string tbbh, string attachmentName, object userState) {
            if ((this.GetAttachmentOperationCompleted == null)) {
                this.GetAttachmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAttachmentOperationCompleted);
            }
            this.InvokeAsync("GetAttachment", new object[] {
                        xzqdm,
                        tblx,
                        tbbh,
                        attachmentName}, this.GetAttachmentOperationCompleted, userState);
        }
        
        private void OnGetAttachmentOperationCompleted(object arg) {
            if ((this.GetAttachmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAttachmentCompleted(this, new GetAttachmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NoReceiveDatas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SingleResultOfString NoReceiveDatas(ReceiveEntity[] xzqs) {
            object[] results = this.Invoke("NoReceiveDatas", new object[] {
                        xzqs});
            return ((SingleResultOfString)(results[0]));
        }
        
        /// <remarks/>
        public void NoReceiveDatasAsync(ReceiveEntity[] xzqs) {
            this.NoReceiveDatasAsync(xzqs, null);
        }
        
        /// <remarks/>
        public void NoReceiveDatasAsync(ReceiveEntity[] xzqs, object userState) {
            if ((this.NoReceiveDatasOperationCompleted == null)) {
                this.NoReceiveDatasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNoReceiveDatasOperationCompleted);
            }
            this.InvokeAsync("NoReceiveDatas", new object[] {
                        xzqs}, this.NoReceiveDatasOperationCompleted, userState);
        }
        
        private void OnNoReceiveDatasOperationCompleted(object arg) {
            if ((this.NoReceiveDatasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NoReceiveDatasCompleted(this, new NoReceiveDatasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReceiveDatas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SingleResultOfString ReceiveDatas(ReceiveEntity[] xzqs) {
            object[] results = this.Invoke("ReceiveDatas", new object[] {
                        xzqs});
            return ((SingleResultOfString)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveDatasAsync(ReceiveEntity[] xzqs) {
            this.ReceiveDatasAsync(xzqs, null);
        }
        
        /// <remarks/>
        public void ReceiveDatasAsync(ReceiveEntity[] xzqs, object userState) {
            if ((this.ReceiveDatasOperationCompleted == null)) {
                this.ReceiveDatasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveDatasOperationCompleted);
            }
            this.InvokeAsync("ReceiveDatas", new object[] {
                        xzqs}, this.ReceiveDatasOperationCompleted, userState);
        }
        
        private void OnReceiveDatasOperationCompleted(object arg) {
            if ((this.ReceiveDatasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveDatasCompleted(this, new ReceiveDatasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveHLFJList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveHLFJList(string[] xzqdm, string[] tblx, string[] tbbsm, string[] savename, string[] fjlx, byte[][] fj) {
            this.Invoke("SaveHLFJList", new object[] {
                        xzqdm,
                        tblx,
                        tbbsm,
                        savename,
                        fjlx,
                        fj});
        }
        
        /// <remarks/>
        public void SaveHLFJListAsync(string[] xzqdm, string[] tblx, string[] tbbsm, string[] savename, string[] fjlx, byte[][] fj) {
            this.SaveHLFJListAsync(xzqdm, tblx, tbbsm, savename, fjlx, fj, null);
        }
        
        /// <remarks/>
        public void SaveHLFJListAsync(string[] xzqdm, string[] tblx, string[] tbbsm, string[] savename, string[] fjlx, byte[][] fj, object userState) {
            if ((this.SaveHLFJListOperationCompleted == null)) {
                this.SaveHLFJListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveHLFJListOperationCompleted);
            }
            this.InvokeAsync("SaveHLFJList", new object[] {
                        xzqdm,
                        tblx,
                        tbbsm,
                        savename,
                        fjlx,
                        fj}, this.SaveHLFJListOperationCompleted, userState);
        }
        
        private void OnSaveHLFJListOperationCompleted(object arg) {
            if ((this.SaveHLFJListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveHLFJListCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveHLFJ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveHLFJ(string xzqdm, string tblx, string tbbsm, string savename, string fjlx, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] fj) {
            this.Invoke("SaveHLFJ", new object[] {
                        xzqdm,
                        tblx,
                        tbbsm,
                        savename,
                        fjlx,
                        fj});
        }
        
        /// <remarks/>
        public void SaveHLFJAsync(string xzqdm, string tblx, string tbbsm, string savename, string fjlx, byte[] fj) {
            this.SaveHLFJAsync(xzqdm, tblx, tbbsm, savename, fjlx, fj, null);
        }
        
        /// <remarks/>
        public void SaveHLFJAsync(string xzqdm, string tblx, string tbbsm, string savename, string fjlx, byte[] fj, object userState) {
            if ((this.SaveHLFJOperationCompleted == null)) {
                this.SaveHLFJOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveHLFJOperationCompleted);
            }
            this.InvokeAsync("SaveHLFJ", new object[] {
                        xzqdm,
                        tblx,
                        tbbsm,
                        savename,
                        fjlx,
                        fj}, this.SaveHLFJOperationCompleted, userState);
        }
        
        private void OnSaveHLFJOperationCompleted(object arg) {
            if ((this.SaveHLFJCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveHLFJCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReceiveLxjzDatas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SingleResultOfString ReceiveLxjzDatas(string[] xzqs, bool isMerge) {
            object[] results = this.Invoke("ReceiveLxjzDatas", new object[] {
                        xzqs,
                        isMerge});
            return ((SingleResultOfString)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveLxjzDatasAsync(string[] xzqs, bool isMerge) {
            this.ReceiveLxjzDatasAsync(xzqs, isMerge, null);
        }
        
        /// <remarks/>
        public void ReceiveLxjzDatasAsync(string[] xzqs, bool isMerge, object userState) {
            if ((this.ReceiveLxjzDatasOperationCompleted == null)) {
                this.ReceiveLxjzDatasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveLxjzDatasOperationCompleted);
            }
            this.InvokeAsync("ReceiveLxjzDatas", new object[] {
                        xzqs,
                        isMerge}, this.ReceiveLxjzDatasOperationCompleted, userState);
        }
        
        private void OnReceiveLxjzDatasOperationCompleted(object arg) {
            if ((this.ReceiveLxjzDatasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveLxjzDatasCompleted(this, new ReceiveLxjzDatasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpLoadFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpLoadFile(string fileName, string folderName, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data, int dataLength, string parameters, bool firstChunk, bool lastChunk, string xzqdm) {
            object[] results = this.Invoke("UpLoadFile", new object[] {
                        fileName,
                        folderName,
                        data,
                        dataLength,
                        parameters,
                        firstChunk,
                        lastChunk,
                        xzqdm});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpLoadFileAsync(string fileName, string folderName, byte[] data, int dataLength, string parameters, bool firstChunk, bool lastChunk, string xzqdm) {
            this.UpLoadFileAsync(fileName, folderName, data, dataLength, parameters, firstChunk, lastChunk, xzqdm, null);
        }
        
        /// <remarks/>
        public void UpLoadFileAsync(string fileName, string folderName, byte[] data, int dataLength, string parameters, bool firstChunk, bool lastChunk, string xzqdm, object userState) {
            if ((this.UpLoadFileOperationCompleted == null)) {
                this.UpLoadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpLoadFileOperationCompleted);
            }
            this.InvokeAsync("UpLoadFile", new object[] {
                        fileName,
                        folderName,
                        data,
                        dataLength,
                        parameters,
                        firstChunk,
                        lastChunk,
                        xzqdm}, this.UpLoadFileOperationCompleted, userState);
        }
        
        private void OnUpLoadFileOperationCompleted(object arg) {
            if ((this.UpLoadFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpLoadFileCompleted(this, new UpLoadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ImportData(ImportParams[] importParams, string xzqdm) {
            object[] results = this.Invoke("ImportData", new object[] {
                        importParams,
                        xzqdm});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ImportDataAsync(ImportParams[] importParams, string xzqdm) {
            this.ImportDataAsync(importParams, xzqdm, null);
        }
        
        /// <remarks/>
        public void ImportDataAsync(ImportParams[] importParams, string xzqdm, object userState) {
            if ((this.ImportDataOperationCompleted == null)) {
                this.ImportDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportDataOperationCompleted);
            }
            this.InvokeAsync("ImportData", new object[] {
                        importParams,
                        xzqdm}, this.ImportDataOperationCompleted, userState);
        }
        
        private void OnImportDataOperationCompleted(object arg) {
            if ((this.ImportDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportDataCompleted(this, new ImportDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteTaskDb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteTaskDb(string[] deleteOrgDms) {
            this.Invoke("DeleteTaskDb", new object[] {
                        deleteOrgDms});
        }
        
        /// <remarks/>
        public void DeleteTaskDbAsync(string[] deleteOrgDms) {
            this.DeleteTaskDbAsync(deleteOrgDms, null);
        }
        
        /// <remarks/>
        public void DeleteTaskDbAsync(string[] deleteOrgDms, object userState) {
            if ((this.DeleteTaskDbOperationCompleted == null)) {
                this.DeleteTaskDbOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteTaskDbOperationCompleted);
            }
            this.InvokeAsync("DeleteTaskDb", new object[] {
                        deleteOrgDms}, this.DeleteTaskDbOperationCompleted, userState);
        }
        
        private void OnDeleteTaskDbOperationCompleted(object arg) {
            if ((this.DeleteTaskDbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteTaskDbCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BackData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BackData(string[] backOrgDms, string backPC) {
            this.Invoke("BackData", new object[] {
                        backOrgDms,
                        backPC});
        }
        
        /// <remarks/>
        public void BackDataAsync(string[] backOrgDms, string backPC) {
            this.BackDataAsync(backOrgDms, backPC, null);
        }
        
        /// <remarks/>
        public void BackDataAsync(string[] backOrgDms, string backPC, object userState) {
            if ((this.BackDataOperationCompleted == null)) {
                this.BackDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBackDataOperationCompleted);
            }
            this.InvokeAsync("BackData", new object[] {
                        backOrgDms,
                        backPC}, this.BackDataOperationCompleted, userState);
        }
        
        private void OnBackDataOperationCompleted(object arg) {
            if ((this.BackDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BackDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OSSShptodb", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void OSSShptodb(ImportParams[] importParams, string xzqdm) {
            this.Invoke("OSSShptodb", new object[] {
                        importParams,
                        xzqdm});
        }
        
        /// <remarks/>
        public void OSSShptodbAsync(ImportParams[] importParams, string xzqdm) {
            this.OSSShptodbAsync(importParams, xzqdm, null);
        }
        
        /// <remarks/>
        public void OSSShptodbAsync(ImportParams[] importParams, string xzqdm, object userState) {
            if ((this.OSSShptodbOperationCompleted == null)) {
                this.OSSShptodbOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOSSShptodbOperationCompleted);
            }
            this.InvokeAsync("OSSShptodb", new object[] {
                        importParams,
                        xzqdm}, this.OSSShptodbOperationCompleted, userState);
        }
        
        private void OnOSSShptodbOperationCompleted(object arg) {
            if ((this.OSSShptodbCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OSSShptodbCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLayerState", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateLayerState(string tbbh, string xzqdm, int status, string sbbh) {
            object[] results = this.Invoke("UpdateLayerState", new object[] {
                        tbbh,
                        xzqdm,
                        status,
                        sbbh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLayerStateAsync(string tbbh, string xzqdm, int status, string sbbh) {
            this.UpdateLayerStateAsync(tbbh, xzqdm, status, sbbh, null);
        }
        
        /// <remarks/>
        public void UpdateLayerStateAsync(string tbbh, string xzqdm, int status, string sbbh, object userState) {
            if ((this.UpdateLayerStateOperationCompleted == null)) {
                this.UpdateLayerStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLayerStateOperationCompleted);
            }
            this.InvokeAsync("UpdateLayerState", new object[] {
                        tbbh,
                        xzqdm,
                        status,
                        sbbh}, this.UpdateLayerStateOperationCompleted, userState);
        }
        
        private void OnUpdateLayerStateOperationCompleted(object arg) {
            if ((this.UpdateLayerStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLayerStateCompleted(this, new UpdateLayerStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryLayer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QueryLayer(string xzqdm, int status, string sbbh) {
            object[] results = this.Invoke("QueryLayer", new object[] {
                        xzqdm,
                        status,
                        sbbh});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QueryLayerAsync(string xzqdm, int status, string sbbh) {
            this.QueryLayerAsync(xzqdm, status, sbbh, null);
        }
        
        /// <remarks/>
        public void QueryLayerAsync(string xzqdm, int status, string sbbh, object userState) {
            if ((this.QueryLayerOperationCompleted == null)) {
                this.QueryLayerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryLayerOperationCompleted);
            }
            this.InvokeAsync("QueryLayer", new object[] {
                        xzqdm,
                        status,
                        sbbh}, this.QueryLayerOperationCompleted, userState);
        }
        
        private void OnQueryLayerOperationCompleted(object arg) {
            if ((this.QueryLayerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryLayerCompleted(this, new QueryLayerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Uploadattachmsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Uploadattachmsg(string jsonmsg) {
            object[] results = this.Invoke("Uploadattachmsg", new object[] {
                        jsonmsg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadattachmsgAsync(string jsonmsg) {
            this.UploadattachmsgAsync(jsonmsg, null);
        }
        
        /// <remarks/>
        public void UploadattachmsgAsync(string jsonmsg, object userState) {
            if ((this.UploadattachmsgOperationCompleted == null)) {
                this.UploadattachmsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadattachmsgOperationCompleted);
            }
            this.InvokeAsync("Uploadattachmsg", new object[] {
                        jsonmsg}, this.UploadattachmsgOperationCompleted, userState);
        }
        
        private void OnUploadattachmsgOperationCompleted(object arg) {
            if ((this.UploadattachmsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadattachmsgCompleted(this, new UploadattachmsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleResultOfArrayOfByte : Result {
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingleResultOfString))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingleResultOfArrayOfByte))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result {
        
        private int resultCodeField;
        
        private string errorMsgField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TableField {
        
        private string nameField;
        
        private string aliasField;
        
        private TypeCode fieldTypeField;
        
        private bool isNullField;
        
        private bool isPrimaryKeyField;
        
        private int fieldLengthField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        public TypeCode FieldType {
            get {
                return this.fieldTypeField;
            }
            set {
                this.fieldTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsNull {
            get {
                return this.isNullField;
            }
            set {
                this.isNullField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPrimaryKey {
            get {
                return this.isPrimaryKeyField;
            }
            set {
                this.isPrimaryKeyField = value;
            }
        }
        
        /// <remarks/>
        public int FieldLength {
            get {
                return this.fieldLengthField;
            }
            set {
                this.fieldLengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TypeCode {
        
        /// <remarks/>
        Empty,
        
        /// <remarks/>
        Object,
        
        /// <remarks/>
        DBNull,
        
        /// <remarks/>
        Boolean,
        
        /// <remarks/>
        Char,
        
        /// <remarks/>
        SByte,
        
        /// <remarks/>
        Byte,
        
        /// <remarks/>
        Int16,
        
        /// <remarks/>
        UInt16,
        
        /// <remarks/>
        Int32,
        
        /// <remarks/>
        UInt32,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        UInt64,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        Double,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        String,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportParams {
        
        private string layerNameField;
        
        private string tableNameField;
        
        private TableField[] fieldsField;
        
        private bool isAppendField;
        
        private string jasonVectorDataTemplateField;
        
        private string selectLayerNameField;
        
        private string batchDataBsmField;
        
        private string oSSObjectNameField;
        
        /// <remarks/>
        public string LayerName {
            get {
                return this.layerNameField;
            }
            set {
                this.layerNameField = value;
            }
        }
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        public TableField[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        public bool IsAppend {
            get {
                return this.isAppendField;
            }
            set {
                this.isAppendField = value;
            }
        }
        
        /// <remarks/>
        public string JasonVectorDataTemplate {
            get {
                return this.jasonVectorDataTemplateField;
            }
            set {
                this.jasonVectorDataTemplateField = value;
            }
        }
        
        /// <remarks/>
        public string SelectLayerName {
            get {
                return this.selectLayerNameField;
            }
            set {
                this.selectLayerNameField = value;
            }
        }
        
        /// <remarks/>
        public string BatchDataBsm {
            get {
                return this.batchDataBsmField;
            }
            set {
                this.batchDataBsmField = value;
            }
        }
        
        /// <remarks/>
        public string OSSObjectName {
            get {
                return this.oSSObjectNameField;
            }
            set {
                this.oSSObjectNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveEntity {
        
        private string xZQDMField;
        
        private string fILENAMEField;
        
        private string bSMField;
        
        private string rYNAMEField;
        
        /// <remarks/>
        public string XZQDM {
            get {
                return this.xZQDMField;
            }
            set {
                this.xZQDMField = value;
            }
        }
        
        /// <remarks/>
        public string FILENAME {
            get {
                return this.fILENAMEField;
            }
            set {
                this.fILENAMEField = value;
            }
        }
        
        /// <remarks/>
        public string BSM {
            get {
                return this.bSMField;
            }
            set {
                this.bSMField = value;
            }
        }
        
        /// <remarks/>
        public string RYNAME {
            get {
                return this.rYNAMEField;
            }
            set {
                this.rYNAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleResultOfString : Result {
        
        private string dataField;
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetAttachmentCompletedEventHandler(object sender, GetAttachmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAttachmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAttachmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SingleResultOfArrayOfByte Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SingleResultOfArrayOfByte)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void NoReceiveDatasCompletedEventHandler(object sender, NoReceiveDatasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NoReceiveDatasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NoReceiveDatasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SingleResultOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SingleResultOfString)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ReceiveDatasCompletedEventHandler(object sender, ReceiveDatasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveDatasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveDatasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SingleResultOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SingleResultOfString)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveHLFJListCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SaveHLFJCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ReceiveLxjzDatasCompletedEventHandler(object sender, ReceiveLxjzDatasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveLxjzDatasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveLxjzDatasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SingleResultOfString Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SingleResultOfString)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void UpLoadFileCompletedEventHandler(object sender, UpLoadFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpLoadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpLoadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ImportDataCompletedEventHandler(object sender, ImportDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void DeleteTaskDbCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void BackDataCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void OSSShptodbCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void UpdateLayerStateCompletedEventHandler(object sender, UpdateLayerStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLayerStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLayerStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void QueryLayerCompletedEventHandler(object sender, QueryLayerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryLayerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryLayerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void UploadattachmsgCompletedEventHandler(object sender, UploadattachmsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadattachmsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadattachmsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591